[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "*"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/twikoo"
  status = 200
  force = true
